final List<Map<String, String>> countryCodes = [
  {'code': '+1', 'name': 'United States', 'flag': '🇺🇸'},
  {'code': '+44', 'name': 'United Kingdom', 'flag': '🇬🇧'},
  {'code': '+91', 'name': 'India', 'flag': '🇮🇳'},
  {'code': '+61', 'name': 'Australia', 'flag': '🇦🇺'},
  {'code': '+81', 'name': 'Japan', 'flag': '🇯🇵'},
  {'code': '+49', 'name': 'Germany', 'flag': '🇩🇪'},
  {'code': '+33', 'name': 'France', 'flag': '🇫🇷'},
  {'code': '+39', 'name': 'Italy', 'flag': '🇮🇹'},
  {'code': '+86', 'name': 'China', 'flag': '🇨🇳'},
  {'code': '+7', 'name': 'Russia', 'flag': '🇷🇺'},
  {'code': '+34', 'name': 'Spain', 'flag': '🇪🇸'},
  {'code': '+55', 'name': 'Brazil', 'flag': '🇧🇷'},
  {'code': '+27', 'name': 'South Africa', 'flag': '🇿🇦'},
  {'code': '+82', 'name': 'South Korea', 'flag': '🇰🇷'},
  {'code': '+31', 'name': 'Netherlands', 'flag': '🇳🇱'},
  {'code': '+46', 'name': 'Sweden', 'flag': '🇸🇪'},
  {'code': '+41', 'name': 'Switzerland', 'flag': '🇨🇭'},
  {'code': '+32', 'name': 'Belgium', 'flag': '🇧🇪'},
  {'code': '+52', 'name': 'Mexico', 'flag': '🇲🇽'},
  {'code': '+64', 'name': 'New Zealand', 'flag': '🇳🇿'},
  {'code': '+47', 'name': 'Norway', 'flag': '🇳🇴'},
  {'code': '+45', 'name': 'Denmark', 'flag': '🇩🇰'},
  {'code': '+48', 'name': 'Poland', 'flag': '🇵🇱'},
  {'code': '+30', 'name': 'Greece', 'flag': '🇬🇷'},
  {'code': '+351', 'name': 'Portugal', 'flag': '🇵🇹'},
  {'code': '+353', 'name': 'Ireland', 'flag': '🇮🇪'},
  {'code': '+358', 'name': 'Finland', 'flag': '🇫🇮'},
  {'code': '+420', 'name': 'Czech Republic', 'flag': '🇨🇿'},
  {'code': '+36', 'name': 'Hungary', 'flag': '🇭🇺'},
  {'code': '+386', 'name': 'Slovenia', 'flag': '🇸🇮'},
  {'code': '+421', 'name': 'Slovakia', 'flag': '🇸🇰'},
  {'code': '+372', 'name': 'Estonia', 'flag': '🇪🇪'},
  {'code': '+370', 'name': 'Lithuania', 'flag': '🇱🇹'},
  {'code': '+371', 'name': 'Latvia', 'flag': '🇱🇻'},
  {'code': '+40', 'name': 'Romania', 'flag': '🇷🇴'},
  {'code': '+380', 'name': 'Ukraine', 'flag': '🇺🇦'},
  {'code': '+375', 'name': 'Belarus', 'flag': '🇧🇾'},
  {'code': '+359', 'name': 'Bulgaria', 'flag': '🇧🇬'},
  {'code': '+385', 'name': 'Croatia', 'flag': '🇭🇷'},
  {'code': '+381', 'name': 'Serbia', 'flag': '🇷🇸'},
  {'code': '+382', 'name': 'Montenegro', 'flag': '🇲🇪'},
  {'code': '+383', 'name': 'Kosovo', 'flag': '🇽🇰'},
  {'code': '+389', 'name': 'North Macedonia', 'flag': '🇲🇰'},
  {'code': '+90', 'name': 'Turkey', 'flag': '🇹🇷'},
  {'code': '+961', 'name': 'Lebanon', 'flag': '🇱🇧'},
  {'code': '+962', 'name': 'Jordan', 'flag': '🇯🇴'},
  {'code': '+963', 'name': 'Syria', 'flag': '🇸🇾'},
  {'code': '+964', 'name': 'Iraq', 'flag': '🇮🇶'},
  {'code': '+965', 'name': 'Kuwait', 'flag': '🇰🇼'},
  {'code': '+966', 'name': 'Saudi Arabia', 'flag': '🇸🇦'},
  {'code': '+971', 'name': 'United Arab Emirates', 'flag': '🇦🇪'},
  {'code': '+968', 'name': 'Oman', 'flag': '🇴🇲'},
  {'code': '+973', 'name': 'Bahrain', 'flag': '🇧🇭'},
  {'code': '+974', 'name': 'Qatar', 'flag': '🇶🇦'},
  {'code': '+20', 'name': 'Egypt', 'flag': '🇪🇬'},
  {'code': '+212', 'name': 'Morocco', 'flag': '🇲🇦'},
  {'code': '+213', 'name': 'Algeria', 'flag': '🇩🇿'},
  {'code': '+216', 'name': 'Tunisia', 'flag': '🇹🇳'},
  {'code': '+218', 'name': 'Libya', 'flag': '🇱🇾'},
  {'code': '+254', 'name': 'Kenya', 'flag': '🇰🇪'},
  {'code': '+255', 'name': 'Tanzania', 'flag': '🇹🇿'},
  {'code': '+256', 'name': 'Uganda', 'flag': '🇺🇬'},
  {'code': '+260', 'name': 'Zambia', 'flag': '🇿🇲'},
  {'code': '+263', 'name': 'Zimbabwe', 'flag': '🇿🇼'},
  {'code': '+267', 'name': 'Botswana', 'flag': '🇧🇼'},
  {'code': '+258', 'name': 'Mozambique', 'flag': '🇲🇿'},
  {'code': '+250', 'name': 'Rwanda', 'flag': '🇷🇼'},
  {'code': '+251', 'name': 'Ethiopia', 'flag': '🇪🇹'},
  {'code': '+233', 'name': 'Ghana', 'flag': '🇬🇭'},
  {'code': '+234', 'name': 'Nigeria', 'flag': '🇳🇬'},
  {'code': '+237', 'name': 'Cameroon', 'flag': '🇨🇲'},
  {'code': '+221', 'name': 'Senegal', 'flag': '🇸🇳'},
  {'code': '+225', 'name': 'Ivory Coast', 'flag': '🇨🇮'},
  {'code': '+228', 'name': 'Togo', 'flag': '🇹🇬'},
  {'code': '+229', 'name': 'Benin', 'flag': '🇧🇯'},
  {'code': '+223', 'name': 'Mali', 'flag': '🇲🇱'},
  {'code': '+222', 'name': 'Mauritania', 'flag': '🇲🇷'},
  {'code': '+220', 'name': 'Gambia', 'flag': '🇬🇲'},
  {'code': '+374', 'name': 'Armenia', 'flag': '🇦🇲'},
  {'code': '+994', 'name': 'Azerbaijan', 'flag': '🇦🇿'},
  {'code': '+973', 'name': 'Bahrain', 'flag': '🇧🇭'},
  {'code': '+880', 'name': 'Bangladesh', 'flag': '🇧🇩'},
  {'code': '+975', 'name': 'Bhutan', 'flag': '🇧🇹'},
  {'code': '+673', 'name': 'Brunei', 'flag': '🇧🇳'},
  {'code': '+855', 'name': 'Cambodia', 'flag': '🇰🇭'},
  {'code': '+94', 'name': 'Sri Lanka', 'flag': '🇱🇰'},
  {'code': '+66', 'name': 'Thailand', 'flag': '🇹🇭'},
  {'code': '+84', 'name': 'Vietnam', 'flag': '🇻🇳'},
];